version: "3"
services:
  backend-template:
    container_name: backend-template
    build: ./backend/
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/db
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules

  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes: 
      - ./backend/src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: none

volumes:
    db-data:
    pgadmin-data:
