version: "3"
services:
  backend-template:
    container_name: backend-template
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/backend-db
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes: 
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: backend-db

volumes:
    db-data:
    pgadmin-data:
